spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bycmysql@bycmysql
    password: byc123456+
    url: jdbc:mysql://bycmysql.mysql.database.azure.com:3306/spring-cloud?useSSL=true&requireSSL=false
  redis:
    host: biyc.redis.cache.windows.net
    port: 6379
    password: TVvagVPafd1JLf9eQH8tcY48p0QooyekpAzCaAsWMrs=

