spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.174.54.139:3306/spring-cloud
  redis:
    host: biyc.redis.cache.windows.net
    port: 6379
    password: TVvagVPafd1JLf9eQH8tcY48p0QooyekpAzCaAsWMrs=

